<a href="https://colab.research.google.com/github/Chaitali-Pawar/Machine_Learning/blob/master/Homework_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import scipy.io
import os
import re
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split
import sklearn.model_selection
import scipy.io
import os
import re
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split
files = os.listdir("./data")
# Number of folds
nfold=10

kf=sklearn.model_selection.KFold(n_splits=nfold,shuffle=True)

acc=np.zeros((59,nfold))

i =0
for file in files:
  
  index =((re.search('Ch_(.*).mat',file)).group(1))
  mat = scipy.io.loadmat(file)
  X = mat['Ch_Matrix']
  y=mat['y']
  y= np.ravel(y)
  # Loop over the folds
  for isplit,Ind in enumerate(kf.split(X)):
    #print("fold = %d "%isplit)
	 # Get the training data in the split
    Itr,Its=Ind
	
	#Xtr,Xts,Ytr,Yts = train_test_split(X,y,test_size=0.33,shuffle=True) 
    Xtr = X[Itr]
    Ytr = y[Itr]
    Xts = X[Its]
    Yts = y[Its]
    #Scale data to range of -1 and +1
    Xtr_scale = np.interp(Xtr,(Xtr.min(),Xtr.max()),(-1,+1))
    Xts_scale = np.interp(Xts,(Xts.min(),Xts.max()),(-1,+1))
    svc = svm.SVC(probability=False,  kernel='rbf', C=2.8, gamma=.0073,verbose=10)
    svc.fit(Xtr_scale,Ytr)
    yhat = svc.predict(Xts_scale)
    acc[int(index),isplit] =np.mean(yhat == Yts)

#get the mean of accuracies over all splits
acc_mean=np.mean(acc,axis=1)

#pick the one with max accuracy
print ('Max Accuracy is {0:f}'.format(np.max(acc_mean)))

#Maximum Accuracy is for channel
print ('Channel with max accuracy is : {0:d}'.format(np.argmax(acc_mean)))


[LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM]

In [19]:

#question 1
import numpy as np
X = np.array([[3,2,1],
             [2,4,5],
             [1,2,3],
             [0,2,5]])
X_mean = np.mean(X)
print('Mean is : {0:f}'.format(np.mean(X)))

# Sample Covariance
Q = np.cov(X)
print('Sample CoVariance is :')
print(Q)

# compute eigen values and vectors
Values , Vectors = np.linalg.eig(Q)
print('Eigen Values :')
print(Values)

print('Eigen Vectors : ')
print (Vectors)

# find the pca coefficents corresponding to the samples in X
# compute x - xmean
Mean_diff = X - X_mean
Pca_Coeff = Vectors.T.dot(Mean_diff)
print("PCA Coefficents :")
print(Pca_Coeff)
X_new = np.zeros(4,3)
# reconstruct the original samples from the pca coefficents :
for i in range(4):
  for j in range(3):
    X_new[i][j] = X_mean + np.sum()


Mean is : 2.500000
Sample CoVariance is :
[[ 1.         -1.5        -1.         -2.5       ]
 [-1.5         2.33333333  1.5         3.66666667]
 [-1.          1.5         1.          2.5       ]
 [-2.5         3.66666667  2.5         6.33333333]]
Eigen Values :
[ 1.05080582e+01  1.58608435e-01  1.10146918e-16 -1.80894799e-16]
Eigen Vectors : 
[[-0.30836823 -0.07006451  0.26482046 -0.90423089]
 [ 0.46006744  0.82966135  0.28518182 -0.12963556]
 [ 0.30836823  0.07006451 -0.87590683 -0.38568866]
 [ 0.77340547 -0.54940329  0.28518182 -0.12963556]]
PCA Coefficents :
[[-2.78028385  0.30339842  3.70041873]
 [ 0.81854852  1.51919367  0.84077417]
 [ 0.59072501  0.59072501  0.59072501]
 [ 0.51532422  0.51532422  0.51532422]]
0
1
2
3


In [0]:
#question no 3 find the optimal number of PCS
mu ,V = PCA(X)
# V is the PCS
iterations = V.shape[1]
acc = np.zeros(iterations)
for i in range(iterations):
  clf = Classifier()
  #Split the data into train and test
  Xtr,Xts,Ytr,Yts = train_test_split(X,y,test_size=0.25,shuffle=True)
  pca = PCA(n_components=i)
  pca.fit(Xtr)
  #transform the data
  Z_tr = pca.transform(Xtr)
  Z_ts = pca.transform(Xts)
  #fit
  clf.fit(Ztr,ytr)
  yhat = clf.predict(Zts)
  acc[i] = np.mean(yhat == yts)
optimal_number_of_components = np.argmax(acc)
print(optimal_number_of_components)
  
  
  

In [25]:
#question 4:

#fit the PC model with first 500 images and 5 components
Y = reshape(X[0:500,:],shape)
pca = PCA(n_components =5)
pca.fit(Y)
#create an array of approximations of remaining 500
Y = reshape(X[500:1000],shape)
Z =pca.transform(Y)
Yhat = pca.inverse_transform(Z)

[[4 5 6]
 [7 8 9]]


In [0]:
#question 5
U,s,Vtr = svd(Z,full_matrices=False)
#number of Principal Components
number_Of_PC = Vtr
#Mean of data
X_mean = np.mean(X,axis=0)
#compute proportion of variance which is s sqaure
Variance = s ** 2
Proportion_of_Variance = np.cumsum(Variance)/np.sum(Variance)
Variance_Above_90 = np.ravel(np.where(Proportion_of_Variance>90))
#to transform Z we use U*s
#to compute number of Principal Components
number_of_components = Variance_Above_90[0]
#Approximation of Xhat
Xhat = (U[:,:number_of_components] * S[None,:numbr_of_components])dot(Vtr[:number_of_components,:]) +X_mean


In [8]:
top_5_accuracies_index = np.argsort(acc_mean)[-5:];
print ('Max Accuracy is {0:f}'.format(np.max(acc_mean)))
print ('Channel with max accuracy is : {0:d}'.format(np.argmax(acc_mean)))
print(np.argsort(acc_mean)[-5:])
top_five_accuracies = np.zeros(5)
for i in top_5_accuracies_index:
  print(acc_mean[i])

Max Accuracy is 0.542333
Channel with max accuracy is : 51
[10 23 19 30 51]
0.5373595592082987
0.5382830055098962
0.5396255938272745
0.5403140743476877
0.5423333435938478


In [0]:
import os, shutil
folder = './'
for the_file in os.listdir(folder):
    file_path = os.path.join(folder, the_file)
    try:
        if os.path.isfile(file_path):
            os.unlink(file_path)
        #elif os.path.isdir(file_path): shutil.rmtree(file_path)
    except Exception as e:
        print(e)